/**
 * Demo product catalogue — the single source of truth for `prisma/seed.ts`.
 *
 * This is a server-side copy of the storefront's curated catalogue
 * (client/src/data/products.ts + images.ts), so seeded DB records match the
 * brand/UI exactly. Image URLs are the existing Unsplash network URLs
 * (local brand assets can replace them later — see images helper below).
 * Each product carries a stable `id` (mirrors the client id) and a `stock`
 * count for inventory-state testing. Idempotency is by `slug`.
 */

// Unsplash URL helper — mirrors client/src/data/images.ts.
const u = (id: string, w = 1200): string =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

const img = {
  ivoryTee: [u('1521572163474-6864f9cf17ab'), u('1618354691373-d851c5c3a990')],
  linenShirt: [u('1602810318383-e386cc2a3ccf'), u('1600185365483-26d7a4cc7519')],
  slipDress: [u('1595777457583-95e059d581b8'), u('1585487000160-6ebcfceb0d03')],
  wideLegTrouser: [u('1594633312681-425c7b97ccd1'), u('1509551388413-e18d05e0b57e')],
  knitCardigan: [u('1583744946564-b52ac1c389c8'), u('1591047139829-d91aecb6caea')],
  denimJacket: [u('1544022613-e87ca75a784a'), u('1578681994506-b8f463449011')],
  cropTop: [u('1503342217505-b0a15ec3261c'), u('1515886657613-9f3515b0c78f')],
  midiSkirt: [u('1583496661160-fb5886a13d16'), u('1591369822096-ffd140ec948f')],
  coordSet: [u('1552573367-8b48c076c1e2'), u('1554568218-0f1715e72254')],
  poplinShirt: [u('1596755094514-f87e34085b2c'), u('1603252109303-2751441dd157')],
  cottonBlazer: [u('1591369822096-ffd140ec948f', 1000), u('1509551388413-e18d05e0b57e', 1000)],
  ribbedTank: [u('1580106285538-05c8d0e69f42'), u('1503342217505-b0a15ec3261c', 1000)],
  merinoPolo: [u('1583743814966-8936f5b7be1a'), u('1516826957135-700dedea698c')],
  oxfordShirt: [u('1620012253295-c15cc3e65df4'), u('1594938298603-c8148c4dae35')],
  chinoTrouser: [u('1584865288642-42078afe6942'), u('1473966968600-fa801b869a1a')],
  rawDenim: [u('1542272604-787c3835535d'), u('1516257984-b1b4d707412e')],
  overshirt: [u('1611312449408-fcece27cdbb7'), u('1591047139756-eb1e21c0a68b')],
  merinoCrew: [u('1620799140408-edc6dcb6d633'), u('1503341504253-dff4815485f1')],
  wovenShorts: [u('1600185365926-3a2ce3cdb9eb'), u('1591195853828-11db59a44f6b')],
  bomberJacket: [u('1591047139756-eb1e21c0a68b', 1000), u('1578932750294-f5075e85f44a')],
  essentialTee: [u('1503341504253-dff4815485f1'), u('1521572163474-6864f9cf17ab', 1000)],
  cottonPolo: [u('1516826957135-700dedea698c'), u('1583743814966-8936f5b7be1a', 1000)],
  linenTrouser: [u('1473966968600-fa801b869a1a'), u('1584865288642-42078afe6942', 1000)],
  woolCoat: [u('1544441893-675973e31985'), u('1591047139829-d91aecb6caea', 1000)],
};

const clothingSizes = ['XS', 'S', 'M', 'L', 'XL'];
const bottomSizes = ['28', '30', '32', '34', '36'];

// Colour palette — mirrors client/src/data/products.ts.
const c = {
  ivory: { name: 'Ivory', hex: '#f4efe6' },
  black: { name: 'Black', hex: '#111111' },
  charcoal: { name: 'Charcoal', hex: '#2b2b2b' },
  stone: { name: 'Stone', hex: '#c9c1b3' },
  clay: { name: 'Clay', hex: '#8b5e3c' },
  olive: { name: 'Olive', hex: '#5b5a3a' },
  navy: { name: 'Navy', hex: '#1e2a3a' },
  indigo: { name: 'Indigo', hex: '#2f3e5c' },
  sand: { name: 'Sand', hex: '#d9c9a8' },
  rust: { name: 'Rust', hex: '#a04a2b' },
  white: { name: 'Optic white', hex: '#ffffff' },
};

export type SeedGender = 'women' | 'men' | 'unisex';

export interface SeedProduct {
  id: string;
  slug: string;
  title: string;
  gender: SeedGender;
  category: string;
  price: number;
  compareAtPrice?: number;
  images: string[];
  colors: { name: string; hex: string }[];
  sizes: string[];
  soldOutSizes?: string[];
  tags: string[];
  isNew?: boolean;
  onSale?: boolean;
  collection?: string;
  essential?: boolean;
  description: string;
  fabric: string;
  care: string;
  stock: number;
}

export const seedProducts: SeedProduct[] = [
  // ── WOMEN ──────────────────────────────────────────────────────────────────
  {
    id: 'w-ivory-tee',
    slug: 'signature-ivory-tee',
    title: 'Signature Cotton Tee',
    gender: 'women',
    category: 't-shirts',
    price: 1490,
    images: img.ivoryTee,
    colors: [c.ivory, c.black, c.stone],
    sizes: clothingSizes,
    tags: ['everyday', 'basics'],
    isNew: true,
    essential: true,
    collection: 'essentials',
    description:
      'A weighty long-staple cotton tee cut for a relaxed body and clean shoulder. Pre-washed for softness and shape retention.',
    fabric: '220 GSM combed cotton',
    care: 'Machine wash cold. Line dry in shade.',
    stock: 60,
  },
  {
    id: 'w-linen-shirt',
    slug: 'atelier-linen-shirt',
    title: 'Atelier Linen Shirt',
    gender: 'women',
    category: 'shirts',
    price: 3490,
    images: img.linenShirt,
    colors: [c.ivory, c.sand],
    sizes: clothingSizes,
    tags: ['linen', 'summer'],
    isNew: true,
    collection: 'summer-essentials',
    description:
      'A lightweight European linen shirt with a soft camp collar and mother-of-pearl buttons.',
    fabric: '100% European linen',
    care: 'Machine wash cold. Iron warm while damp.',
    stock: 34,
  },
  {
    id: 'w-slip-dress',
    slug: 'silk-slip-dress',
    title: 'Bias Slip Dress',
    gender: 'women',
    category: 'dresses',
    price: 5990,
    compareAtPrice: 7490,
    onSale: true,
    images: img.slipDress,
    colors: [c.charcoal, c.ivory],
    sizes: clothingSizes,
    tags: ['evening'],
    description:
      'Fluid bias-cut satin slip with adjustable straps and a fine french seam finish.',
    fabric: 'Satin-back crepe',
    care: 'Dry clean only.',
    stock: 18,
  },
  {
    id: 'w-wideleg',
    slug: 'wide-leg-trouser',
    title: 'Wide-leg Wool Trouser',
    gender: 'women',
    category: 'trousers',
    price: 4490,
    images: img.wideLegTrouser,
    colors: [c.charcoal, c.stone],
    sizes: bottomSizes,
    soldOutSizes: ['28'],
    tags: ['tailored'],
    collection: 'atelier',
    description:
      'A softly tailored trouser with a high rise, deep pleat and languid wide leg.',
    fabric: 'Italian wool blend',
    care: 'Dry clean recommended.',
    stock: 22,
  },
  {
    id: 'w-knit-cardigan',
    slug: 'merino-cardigan',
    title: 'Fine Merino Cardigan',
    gender: 'women',
    category: 'knitwear',
    price: 4290,
    images: img.knitCardigan,
    colors: [c.ivory, c.charcoal],
    sizes: clothingSizes,
    tags: ['knit'],
    essential: true,
    description:
      'A fine-gauge merino cardigan with tonal shell buttons and rib trims.',
    fabric: '100% extra-fine merino wool',
    care: 'Hand wash cold, dry flat.',
    stock: 28,
  },
  {
    id: 'w-denim-jacket',
    slug: 'workwear-denim-jacket',
    title: 'Workwear Denim Jacket',
    gender: 'women',
    category: 'jackets',
    price: 5490,
    images: img.denimJacket,
    colors: [c.indigo],
    sizes: clothingSizes,
    tags: ['denim'],
    collection: 'workwear',
    description:
      'A boxy denim jacket in rigid Japanese selvedge that wears in beautifully.',
    fabric: '13 oz Japanese selvedge denim',
    care: 'Machine wash cold, inside out.',
    stock: 15,
  },
  {
    id: 'w-crop-top',
    slug: 'ribbed-crop-top',
    title: 'Ribbed Cropped Tank',
    gender: 'women',
    category: 'tops',
    price: 1290,
    images: img.cropTop,
    colors: [c.black, c.ivory, c.olive],
    sizes: clothingSizes,
    tags: ['basics'],
    isNew: true,
    essential: true,
    description:
      'A close-fitting ribbed tank in stretch cotton with a cropped body.',
    fabric: 'Cotton–modal rib',
    care: 'Machine wash cold.',
    stock: 72,
  },
  {
    id: 'w-midi-skirt',
    slug: 'bias-midi-skirt',
    title: 'Bias Midi Skirt',
    gender: 'women',
    category: 'skirts',
    price: 3290,
    images: img.midiSkirt,
    colors: [c.charcoal, c.clay],
    sizes: clothingSizes,
    tags: ['skirt'],
    collection: 'atelier',
    description:
      'A bias-cut satin midi that skims the body with a clean waistband.',
    fabric: 'Satin-back crepe',
    care: 'Dry clean only.',
    stock: 26,
  },
  {
    id: 'w-coord-set',
    slug: 'linen-coord-set',
    title: 'Relaxed Linen Co-ord',
    gender: 'women',
    category: 'co-ord-sets',
    price: 6990,
    images: img.coordSet,
    colors: [c.sand, c.ivory],
    sizes: clothingSizes,
    tags: ['linen', 'summer'],
    isNew: true,
    collection: 'summer-essentials',
    description:
      'A boxy shirt jacket and pull-on trouser cut from washed European linen.',
    fabric: '100% washed linen',
    care: 'Machine wash cold, tumble low.',
    stock: 12,
  },
  {
    id: 'w-poplin-shirt',
    slug: 'poplin-shirt',
    title: 'Cotton Poplin Shirt',
    gender: 'women',
    category: 'shirts',
    price: 2790,
    images: img.poplinShirt,
    colors: [c.white, c.ivory],
    sizes: clothingSizes,
    tags: ['shirt'],
    essential: true,
    description: 'The crisp cotton shirt with a modern shoulder and rounded hem.',
    fabric: 'Long-staple cotton poplin',
    care: 'Machine wash cold. Iron warm.',
    stock: 40,
  },
  {
    id: 'w-cotton-blazer',
    slug: 'cotton-blazer',
    title: 'Unstructured Cotton Blazer',
    gender: 'women',
    category: 'jackets',
    price: 7490,
    compareAtPrice: 8990,
    onSale: true,
    images: img.cottonBlazer,
    colors: [c.stone, c.charcoal],
    sizes: clothingSizes,
    tags: ['blazer', 'tailored'],
    collection: 'atelier',
    description:
      'A softly tailored blazer without shoulder padding, lined only through the back.',
    fabric: 'Cotton–linen twill',
    care: 'Dry clean recommended.',
    stock: 9,
  },
  {
    id: 'w-ribbed-tank',
    slug: 'everyday-tank',
    title: 'Everyday Ribbed Tank',
    gender: 'women',
    category: 'tops',
    price: 990,
    images: img.ribbedTank,
    colors: [c.ivory, c.black, c.olive],
    sizes: clothingSizes,
    tags: ['basics'],
    essential: true,
    description:
      'The straight-cut ribbed tank in a soft cotton blend that layers under everything.',
    fabric: 'Cotton–modal rib',
    care: 'Machine wash cold.',
    stock: 85,
  },

  // ── MEN ─────────────────────────────────────────────────────────────────────
  {
    id: 'm-merino-polo',
    slug: 'merino-polo',
    title: 'Fine Merino Polo',
    gender: 'men',
    category: 'polos',
    price: 3990,
    images: img.merinoPolo,
    colors: [c.navy, c.ivory, c.charcoal],
    sizes: clothingSizes,
    tags: ['polo', 'knit'],
    isNew: true,
    essential: true,
    description: 'A fine-gauge merino polo with a clean placket and tonal buttons.',
    fabric: '100% extra-fine merino wool',
    care: 'Hand wash cold, dry flat.',
    stock: 44,
  },
  {
    id: 'm-oxford-shirt',
    slug: 'oxford-shirt',
    title: 'Everyday Oxford Shirt',
    gender: 'men',
    category: 'shirts',
    price: 2990,
    images: img.oxfordShirt,
    colors: [c.white, c.navy],
    sizes: clothingSizes,
    tags: ['shirt'],
    essential: true,
    collection: 'workwear',
    description:
      'A softly washed oxford in long-staple cotton with a button-down collar.',
    fabric: 'Long-staple oxford cotton',
    care: 'Machine wash cold.',
    stock: 50,
  },
  {
    id: 'm-chino',
    slug: 'cotton-chino',
    title: 'Garment-dyed Chino',
    gender: 'men',
    category: 'trousers',
    price: 3490,
    images: img.chinoTrouser,
    colors: [c.stone, c.olive, c.charcoal],
    sizes: bottomSizes,
    tags: ['chino'],
    collection: 'workwear',
    description: 'A garment-dyed chino with a slight taper and clean side seams.',
    fabric: 'Peached cotton twill',
    care: 'Machine wash cold.',
    stock: 38,
  },
  {
    id: 'm-raw-denim',
    slug: 'raw-selvedge-denim',
    title: 'Raw Selvedge Denim',
    gender: 'men',
    category: 'jeans',
    price: 5490,
    images: img.rawDenim,
    colors: [c.indigo],
    sizes: bottomSizes,
    tags: ['denim'],
    description:
      'A straight-leg raw denim in Japanese selvedge that fades to your wear.',
    fabric: '14 oz Japanese selvedge',
    care: 'Wash rarely. Cold, inside out.',
    stock: 20,
  },
  {
    id: 'm-overshirt',
    slug: 'wool-overshirt',
    title: 'Wool Flannel Overshirt',
    gender: 'men',
    category: 'overshirts',
    price: 5990,
    compareAtPrice: 6990,
    onSale: true,
    images: img.overshirt,
    colors: [c.charcoal, c.olive],
    sizes: clothingSizes,
    tags: ['overshirt', 'outerwear'],
    collection: 'weekend',
    description:
      'A brushed wool overshirt with double chest pockets — a layer above a tee.',
    fabric: 'Wool flannel',
    care: 'Dry clean recommended.',
    stock: 16,
  },
  {
    id: 'm-merino-crew',
    slug: 'merino-crew',
    title: 'Merino Crew Sweater',
    gender: 'men',
    category: 'knitwear',
    price: 4490,
    images: img.merinoCrew,
    colors: [c.ivory, c.navy, c.charcoal],
    sizes: clothingSizes,
    tags: ['knit'],
    essential: true,
    description: 'A fine-gauge merino crew that layers cleanly under a jacket.',
    fabric: '100% extra-fine merino wool',
    care: 'Hand wash cold, dry flat.',
    stock: 33,
  },
  {
    id: 'm-woven-shorts',
    slug: 'woven-shorts',
    title: 'Washed Cotton Shorts',
    gender: 'men',
    category: 'shorts',
    price: 2290,
    images: img.wovenShorts,
    colors: [c.stone, c.olive],
    sizes: bottomSizes,
    tags: ['summer'],
    isNew: true,
    collection: 'summer-essentials',
    description: 'A relaxed 7-inch short in washed cotton with a drawcord waist.',
    fabric: 'Washed cotton canvas',
    care: 'Machine wash cold.',
    stock: 47,
  },
  {
    id: 'm-bomber',
    slug: 'cotton-bomber',
    title: 'Cotton Bomber',
    gender: 'men',
    category: 'jackets',
    price: 6990,
    images: img.bomberJacket,
    colors: [c.olive, c.charcoal],
    sizes: clothingSizes,
    tags: ['outerwear'],
    collection: 'weekend',
    description:
      'A cotton bomber with ribbed trims and a clean welt pocket at the chest.',
    fabric: 'Cotton canvas',
    care: 'Machine wash cold.',
    stock: 14,
  },
  {
    id: 'm-essential-tee',
    slug: 'essential-tee',
    title: 'Essential Cotton Tee',
    gender: 'men',
    category: 't-shirts',
    price: 1290,
    images: img.essentialTee,
    colors: [c.ivory, c.black, c.olive, c.navy],
    sizes: clothingSizes,
    tags: ['basics'],
    isNew: true,
    essential: true,
    collection: 'essentials',
    description: 'A weighty jersey tee that holds its shape wash after wash.',
    fabric: '220 GSM combed cotton',
    care: 'Machine wash cold.',
    stock: 90,
  },
  {
    id: 'm-cotton-polo',
    slug: 'cotton-polo',
    title: 'Piqué Cotton Polo',
    gender: 'men',
    category: 'polos',
    price: 2490,
    images: img.cottonPolo,
    colors: [c.ivory, c.navy, c.olive],
    sizes: clothingSizes,
    tags: ['polo'],
    essential: true,
    description:
      'A classic piqué polo in mercerised cotton with mother-of-pearl buttons.',
    fabric: 'Mercerised cotton piqué',
    care: 'Machine wash cold.',
    stock: 55,
  },
  {
    id: 'm-linen-trouser',
    slug: 'linen-trouser',
    title: 'Pull-on Linen Trouser',
    gender: 'men',
    category: 'trousers',
    price: 3790,
    images: img.linenTrouser,
    colors: [c.sand, c.ivory],
    sizes: bottomSizes,
    tags: ['linen', 'summer'],
    isNew: true,
    collection: 'summer-essentials',
    description:
      'A pull-on linen trouser with a covered elastic waist and roomy leg.',
    fabric: '100% washed linen',
    care: 'Machine wash cold.',
    stock: 31,
  },
  {
    id: 'm-wool-coat',
    slug: 'wool-topcoat',
    title: 'Long Wool Topcoat',
    gender: 'men',
    category: 'jackets',
    price: 12490,
    compareAtPrice: 14990,
    onSale: true,
    images: img.woolCoat,
    colors: [c.charcoal, c.stone],
    sizes: clothingSizes,
    tags: ['outerwear'],
    collection: 'atelier',
    description: 'A knee-length topcoat in Italian wool with a clean notch lapel.',
    fabric: 'Italian wool blend',
    care: 'Dry clean only.',
    stock: 7,
  },
];
